CREATE TABLE IF NOT EXISTS v_sessions
(
    id Int32,
    client_id String,
    domain Nullable(String),
    city Nullable(String),
    region Nullable(String),
    browser Nullable(String),
    device_category Nullable(String),
    date Nullable(String),
    date_dt Nullable(Date),
    pageviews Nullable(Int32),
    campaign Nullable(String),
    keyword Nullable(String),
    medium Nullable(String),
    medium_group Nullable(String),
    source Nullable(String),
    sessions Nullable(Int32),
    goal_completion_location Nullable(String),
    conversion Nullable(Int32),
    source_conv Nullable(String),
    ad_cost Nullable(Float64),
    sale Nullable(Int32),
    model_ga_name Nullable(String),
    crm_city Nullable(String),
    count_cost Nullable(Int32),
    dealer_meet Nullable(Int32),
    crm_sale Nullable(Int32),
    brand_name Nullable(String),
    class_name Nullable(String),
    model_name Nullable(String),
    price_original Nullable(Float64),
    currency_code Nullable(String),
    price_rub Nullable(Float64),
    gross_profit_rub Nullable(Float64),
    contribution_margin_rub Nullable(Float64)
)
ENGINE = MergeTree
ORDER BY id;
