SELECT
	CAST(id as int) as id,
	CAST(client_id as varchar(100)) as client_id,
	domain,
	city,
	region,
	browser,
	device_category,
	CAST(date as date) as date,
	CAST(pageviews as int) as pageviews,
	campaign,
	keyword,
	medium,
	source,
	CAST(avg_session_duration as decimal(18, 6)) as avg_session_duration,
	CAST(bounce_rate as decimal(18, 6)) as bounce_rate,
	CAST(sessions as int) as sessions,
	goal_completion_location,
	CAST(goal_completions as int) as goal_completions,
	CAST(goal_conversion_rate as decimal(18, 6)) as goal_conversion_rate,
	CAST(goal_value as decimal(18, 2)) as goal_value,
	CAST(conversion as int) as conversion,
	source_conv,
	CAST(ad_cost as decimal(18, 2)) as ad_cost,
	CAST(sale as int) as sale,
	model_ga_name,
	CAST(model_ga_id as int) as model_ga_id
FROM {{ source('raw', 'ga_sessions') }}
