services:
  postgres:
    image: postgres:15-alpine
    container_name: car_dealer_postgres

    env_file:
      - .env

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "15432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  airflow_postgres:
    image: postgres:13
    container_name: airflow_postgres_autodealer

    restart: unless-stopped

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U airflow -d airflow"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  airflow:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: airflow_autodealer

    restart: unless-stopped

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow

      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"

      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      _AIRFLOW_WWW_USER_FIRSTNAME: Ilya
      _AIRFLOW_WWW_USER_LASTNAME: Lugovoi
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com

      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 15432
      POSTGRES_DB: car_dealer
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - .:/opt/airflow/project
      - ./airflow/dags:/opt/airflow/dags

    ports:
      - "8081:8080"

    command: standalone

    depends_on:
      airflow_postgres:
        condition: service_healthy


volumes:
  postgres_data:
  airflow_postgres_data: